name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-update.yaml@v1
    with:
      rock-name: grafana
      source-repo: grafana/grafana
      check-go: true
      update-script: |
        # The caller must provide \$application_src and \$rockcraft_yaml
        #   \$application_src: The root folder of the cloned upstream project
        #   \$rockcraft_yaml: Path of the rockcraft.yaml to update
        #
        ## grafana-ui dependency
        source_tag=$(yq .parts.grafana.source-tag $rockcraft_yaml)
        tag="\$source_tag" yq -i '.parts.grafana-ui.source-tag = strenv(tag)' $rockcraft_yaml
    secrets: inherit
